version: "3"
services:
  app:
    image: python:3.9-slim
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    command: >
      sh -c "
        # 依存パッケージのインストール
        pip install --no-cache-dir -r requirements.txt &&
        # データベースが起動するまで待機
        sleep 5 &&
        # データベースの初期化（マイグレーション実行）
        alembic upgrade head &&
        # アプリケーション起動
        python main.py
      "

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=hinban_db
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    depends_on:
      mysql:
        condition: service_healthy
    ports:
    - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_PORT=3306
